# Generated by Django 4.1.7 on 2023-08-10 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anterior', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('consumo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('exceso', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cargo_mes', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cargo_exceso', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cargo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('mes', models.IntegerField(default=0)),
                ('ciclo', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField()),
                ('id_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cuenta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id_cuenta'],
            },
        ),
    ]
