# Generated by Django 4.1.7 on 2023-08-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lectura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='mes',
            field=models.CharField(default='No Asignado', max_length=250),
        ),
    ]
