# Generated by Django 4.1.7 on 2023-08-03 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('dpi', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=350)),
                ('direccion', models.CharField(max_length=750)),
                ('telefono', models.CharField(max_length=8)),
                ('correo', models.CharField(blank=True, default='S/C', max_length=250, null=True)),
                ('fecha', models.DateTimeField()),
                ('estado', models.IntegerField(default=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-apellido'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=750)),
                ('limite', models.IntegerField(default=0)),
                ('mensual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fecha', models.DateTimeField()),
                ('dpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id_cuenta'],
            },
        ),
    ]
