# Generated by Django 4.1.7 on 2023-08-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='limite',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='mensual',
        ),
    ]
