# Generated by Django 4.1.7 on 2023-08-21 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0003_initial'),
        ('Cliente', '0002_remove_cuenta_limite_remove_cuenta_mensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Servicios.servicio'),
            preserve_default=False,
        ),
    ]
