# Generated by Django 4.1 on 2023-10-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_cuenta_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
