# Generated by Django 4.1.7 on 2023-08-21 17:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_Servicio', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cuenta', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('derecho', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
            options={
                'ordering': ['-id_Servicio'],
            },
        ),
    ]
