# Generated by Django 4.1.7 on 2023-08-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicios',
        ),
    ]
