# Generated by Django 3.2.9 on 2023-10-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0004_alter_servicio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
